### ISSUE TITLE
Combat 2.0 tracking

### ISSUE THREAD

**Issue by bleehu** [trowl223/Compound_X#140]
Here is a list of things we need written up and merged to the combat 2.0 superbranch!
Weapons
- [x] pistols - Turtle
- [x] smgs - Bleehu
- [x] shotguns - Bleehu
- [x] carbines - MikBleehue
- [x] battle rifles - Bleehu
- [x] assault rifles - Turtle
- [x] heavy weapons Turtle
- [x] Long Rifles - ~~Bleehu~~ Turtle
- [x] Machine guns - Turtle 
- [x] Rocket Launchers - Bleehu
- [x] Melee Weapons - ~~Turtle~~ 1sourcecontrol
- [x] Throwing Weapons - ~~Turtle~~ 1sourcecontrol

Armor
- [x] Recon - ~~Bleehu~~ 1sourcecontrol
- [x] Light - ~~Bleehu~~ 1sourcecontrol
- [x] Medium - ~~Bleehu~~ 1sourcecontrol
- [x] Heavy - ~~Bleehu~~ 1sourcecontrol
- [x] Full - ~~Bleehu~~ 1sourcecontrol

Armor Hardpoints
- [x] Shields, Cloaking, Other - 1Sourcecontrol

Weapon Attachments
- [x] 1Sourcecontrol

Rules
- [x] Cloaking - 1Sourcecontrol
- [x] Armor - 1Sourcecontrol

Tutorial
- [ ] Tutorials - 1Sourcecontrol

Other
- [x] Feats, updating to c2.0 - 1Sourcecontrol
- [x] Classes, updating to c2.0 - 1Sourcecontrol

*edited by 1Sourcecontrol, 8.21.2017*

**Comment by 1sourcecontrol** [comment]
Also im doing armor utilities like Shields and etc.
For more info on what I've done in armor, please see my PR #132

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 before you get started, I'm making a parser for the weapon data. It should handle most of the weapons except for melee, thrown weapons, and shotguns. Luckily melee and thrown weapons have a lot less data that needs to be transferred.

It also won't handle edge cases in heavy weapons or other smaller things, so I/we will have to comb over everything, but it should do most of the heavy lifting for us.

**Comment by Turtlelord26** [comment]
I just now found the spreadsheet you sent out three days ago...in my spam folder. I'm guessing it didn't like "Hey friends" ...?
To be safe, ping me here when the parser goes live.

EDIT: I believe I have solved this issue.

**Comment by 1sourcecontrol** [comment]
Alright bois, I sent you guys an e-mail with the parsed data in it.

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 I sent out another e-mail. Had to redo the parsed data

**Comment by bleehu** [comment]
got it :)

**Comment by trowl223** [comment]
Got the emails, looking through them this week.

**Comment by bleehu** [comment]
@trowl223, I wouldn't worry about these. This is just wrote work. In fact, I would reduce the load by unsubscribing from the superbranch. We're hoping to get your input when we have our ducks in a row and make a PR from the superbranch to dev.

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 , can you hang off on the melee weapons for the time being? I may have to update them pretty soon

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 , you're a machine! Thanks for doing all that work. Unfortunately, I won't have melee weapons done for the next week. Feel free to copy them in without their miss chances, if you like (that's what i'm changing). Granting that the descriptions make sense, melee, thrown weapons, and grenades may be a little hard to piece together with my spreadsheet formatting.
We can always talk about it when i'm back in town.

Also, if somebody takes grenades, the grenades with no description (such as the flashbang) use all the original descriptions except for what I explicitly list in the excel.

**Comment by bleehu** [comment]
@Turtlelord26 way to go man! Thanks for kicking down the doors on this!

**Comment by 1sourcecontrol** [comment]
@Turtlelord26 
I'm taking thrown weapons and melee, if that's alright. It'd probably be easier for me to do it because I didn't format it well on the excel sheet.

**Comment by 1sourcecontrol** [comment]
Living the dream
